DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL,MATRICULA INT NOT NULL);



-- Creación de Odontologos inicial

INSERT INTO ODONTOLOGOS(NOMBRE, APELLIDO, MATRICULA) VALUES ('Juan', 'Lopez',123213), ('Mario', 'Benedetti',345786345), ('Alicia', 'Caronte',34658);